// <auto-generated />
namespace ProjectMinera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Se_elimino_Required_DeLaRelacionConUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Se_elimino_Required_DeLaRelacionConUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201809080752050_Se_elimino_Required_DeLaRelacionConUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
