// <auto-generated />
namespace ProjectMinera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relacion_Usuario_ConTablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacion_Usuario_ConTablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201809071830501_Relacion_Usuario_ConTablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
